version: "3"

services:
  server:
    image: server:0.0.1
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    networks:
      - webnet

  prometheus:
    depends_on:
      -server
    image: prometheus:v2.40.7
    build: ./prom
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - webnet
    
  grafana:
    depends_on:
      -server
      -prometheus
    image: grafana:9.4.2
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - webnet
      
networks:
  webnet:

